language: generic
sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

before_script:
  - docker-compose build
  - docker-compose up -d

script:
  - docker exec -it transport_info /bin/sh -c "npm run lint"

after_success:
  - docker-compose down
  - docker build -t rupak08012/transport_info:latest -t rupak08012/transport_info:$SHA ./app
  - docker tag rupak08012/transport_info registry.heroku.com/$HEROKU_APP_NAME/web
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

deploy:
  provider: script
  script: docker push rupak08012/transport_info:latest;
    docker push rupak08012/transport_info:$SHA;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  skip_cleanup: true
  on:
    branch: main
