version: '3.7'

services:
  transport_info:
    image: transport_info
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: transport_info
    stdin_open: true
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - '/app/node_modules'
      - './app:/app'
    networks:
      - webnet
networks:
  webnet:
